#Start a service
- name: Starts a service based on passed in service name from the template
  hosts: "{{ servername }}"
  gather_facts: no
  tasks:
    - win_service:
        name: "{{ servicename }}"
        state: started