#Start a service
- name: Starts a service based on passed in service name from the template
  hosts: terryedwards519-server1.eastus.cloudapp.azure.com
  gather_facts: no
  tasks:
    - win_service:
        name: wuauserv
        state: started