#Stop a service
- name: Stops a service based on passed in service name from the template
  hosts: terryedwards51-server1
  gather_facts: no
  tasks:
    - win_service:
        name: wuauserv
        state: stopped